title: Dr. Steven P. Mielke # your name (or website title) here
logo: "/images/SPM_photo_mod4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  **Steve Mielke** is a researcher and educator in the Austin, Texas area. He is a former programmer / analyst at NASA, 
  NASA Postdoctoral Program fellow, NIH National Research Service Award recipient, and AAAS Mass Media fellow.
  
  <!--
  His interdisciplinary research interests span topics including molecular biophysics, computation, complexity, 
  history and philosophy of science, and climate change. Current projects apply machine learning and other data science 
  methodologies to a range of problems in these and other areas. 
  -->
  
  <!--
  <br>
  <a href="About.md">About</a>
  -->
    
  <br><br>
  
  <!-- Second description 
  <br><br> -->
  
  CV
  <br><br>
  Professional Certifications
  <br>
  &emsp;&#8226; <a href="https://www.coursera.org/account/accomplishments/verify/6UD6LSLGTEA7">Machine Learning</a>
  <br><br>
  <a href="https://www.linkedin.com/in/steven-mielke/">View My LinkedIn Profile</a> 

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
